name: realtime
services:
  faster-qwen3-tts-api:
    build:
      context: ..
      args:
        - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
        - APT_MIRROR=mirrors.tuna.tsinghua.edu.cn
        - BASE_IMAGE=jetson-containers:r38.2.arm64-sbsa-cu130-24.04
        # - BASE_IMAGE=ghcr.io/nvidia-ai-iot/vllm:0.16.0-g15d76f74e-r38.2-arm64-sbsa-cu130-24.04
      dockerfile: docker/Dockerfile

    image: realtime:faster-qwen3-tts-api
    container_name: faster-qwen3-tts-api
    restart: unless-stopped
    gpus: all

    ports:
      - "23456:8000"

    environment:
      - TZ=Asia/Shanghai

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ../voices:/data/voices
      - ../ckpts:/root/ckpts
      
    command: >
      python api_server.py
      --model_path /root/ckpts/Qwen3-TTS-12Hz-0_6B-Base
      --host 0.0.0.0
      --port 8000
      --device cuda:0
      --dtype bfloat16
      --voices_dir /data/voices
      --log_level debug